### ISSUE TITLE
Support GHC 9.0.1

### ISSUE THREAD

**Issue by asr** [agda/agda#4955]
GHC 9.0.1 was [released](https://mail.haskell.org/pipermail/ghc-devs/2021-February/019477.html). I created this issue for collecting/reporting the required changes/issues.

Known issues upstream (2021-03-24)

- [x] GHC (https://gitlab.haskell.org/ghc/ghc/-/issues/19216)
- [x] GHC (https://gitlab.haskell.org/ghc/ghc/-/issues/19228)
- [x] ListLike (https://github.com/ddssff/listlike/issues/12)
- [x] assoc (https://github.com/haskellari/assoc/issues/10)
- [x] async (https://github.com/simonmar/async/pull/115)
- [x] attoparsec https://github.com/bgamari/attoparsec/pull/6
- [x] blaze-markup https://github.com/jaspervdj/blaze-markup/pull/53
- [x] hashable (https://github.com/tibbe/hashable/issues/193)
- [x] network-uri (https://github.com/haskell/network-uri/issues/55)
- [x] regex-base (https://github.com/haskell-hvr/regex-base/issues/7)
- [x] regex-tdfa (https://github.com/haskell-hvr/regex-tdfa/issues/19)
- [x] split (https://github.com/byorgey/split/issues/9)
- [x] strict (https://github.com/haskellari/strict/issues/26)
- [x] primitive (https://github.com/haskell/primitive/issues/296)
- [ ] stack (waiting a release including the fix to https://github.com/commercialhaskell/stack/issues/5486)
- [x] these (https://github.com/haskellari/these/issues/155)
- [x] time-compat (https://github.com/haskellari/time-compat/issues/21)
- [x] zlib (https://github.com/haskell/zlib/pull/39) (https://github.com/haskell/zlib/issues/42)

Own code base

- [x] hTags (fixed by #5253)

**Comment by asr** [comment]
Running `make install-bin CABAL_OPTS=--allow-newer` with GHC 9.0.1-rc1 I'm getting the errors in https://github.com/haskell/network-uri/issues/55.

**Comment by asr** [comment]
I'm getting some compilation errors like:

```bash
Building library for Agda-2.6.2..
[ 52 of 394] Compiling Agda.Interaction.Highlighting.Dot.Base ( src/full/Agda/Interaction/Highlighting/Dot/Base.hs, dist-2.6.2-ghc-9.0.0/build/Agda/Interaction/Highlighting/Dot/Base.o, dist-2.6.2-ghc-9.0.0/build/Agda/Interaction/Highlighting/Dot/Base.dyn_o )

src/full/Agda/Interaction/Highlighting/Dot/Base.hs:64:21: error:
    • Couldn't match type: ReaderT
                             (Env n) (StateT (DotState n1) Data.Functor.Identity.Identity) a1
                     with: Ord n => ReaderT (Env n) (State (DotState n)) x
      Expected: DotM n x -> DotGraph
        Actual: ReaderT
                  (Env n) (StateT (DotState n1) Data.Functor.Identity.Identity) a1
                -> DotGraph
    • In the expression:
        dsGraph . flip execState initialDotState . flip runReaderT env
      In an equation for ‘runDotM’:
          runDotM env@Env {}
            = dsGraph . flip execState initialDotState . flip runReaderT env
    • Relevant bindings include
        env :: Env n
          (bound at src/full/Agda/Interaction/Highlighting/Dot/Base.hs:64:9)
        runDotM :: Env n -> DotM n x -> DotGraph
          (bound at src/full/Agda/Interaction/Highlighting/Dot/Base.hs:64:1)
   |
64 | runDotM env@Env{} = dsGraph . flip execState initialDotState . flip runReaderT env
```

I can fix the error by removing the constraint `Ord n` from https://github.com/agda/agda/blob/c5400349d7d9cb1e54af19bdb2046b52ecada5bc/src/full/Agda/Interaction/Highlighting/Dot/Base.hs#L61
and adding this constraint to the type of some functions. I don't know if this error is a regression in GHC so I filled https://gitlab.haskell.org/ghc/ghc/-/issues/19216.

**Comment by asr** [comment]
The above error is not a regression in GHC (see https://gitlab.haskell.org/ghc/ghc/-/issues/19216).

**Comment by asr** [comment]
I'm getting the following compilation error:

```
[166 of 394] Compiling Agda.VersionCommit ( src/full/Agda/VersionCommit.hs, dist-2.6.2-ghc-9.0.0/build/Agda/VersionCommit.o, dist-2.6.2-ghc-9.0.0/build/Agda/VersionCommit.dyn_o )

src/full/Agda/VersionCommit.hs:22:13: error: [-Woverlapping-patterns, -Werror=overlapping-patterns]
    Pattern match is redundant
    In an equation for ‘dirty’: dirty | otherwise = ...
   |
22 |           | otherwise          = ""
   |             ^^^^^^^^^
```

I filled https://gitlab.haskell.org/ghc/ghc/-/issues/19228.

**Comment by asr** [comment]
The above error is intentional (see https://gitlab.haskell.org/ghc/ghc/-/issues/19228). I'm writing a proper fix.

**Comment by andreasabel** [comment]
@asr Thanks for the work!
> I can fix the error by removing the constraint `Ord n` from
> 
> https://github.com/agda/agda/blob/c5400349d7d9cb1e54af19bdb2046b52ecada5bc/src/full/Agda/Interaction/Highlighting/Dot/Base.hs#L61

I see that in b0cf67f0b1308b60f02c5a2eae6ad647eadc60c3 you settled for eta-expansion instead.

I would prefer your initial proposal:
> removing the constraint `Ord n`

I think constraints in type definitions such as `type` and `data` are anyway a somewhat obscure and hard-to-understand feature, and to the casual reader of the code eta-expansions are irritating.
At least I would try to eta-contract the code and then see that I get weird compilation errors.  So if there are eta-expansions to fix typing, there should be a comment saying that this eta-expansion is necessary, with link to some justification (e.g. this issue or the GHC issue).

To repeat myself, I would remove the constraints in `type`, `newtype` and `data` to get more idiomatic Haskell.

**Comment by asr** [comment]
GHC 9.0.1 was [released](https://mail.haskell.org/pipermail/ghc-devs/2021-February/019477.html).

**Comment by nad** [comment]
I agree that we should aim to make Agda 2.6.2 build with GHC 9.0.1.

**Comment by asr** [comment]
> I see that in [b0cf67f](https://github.com/agda/agda/commit/b0cf67f0b1308b60f02c5a2eae6ad647eadc60c3) you settled for eta-expansion instead.
> 
> I would prefer your initial proposal:
> 
> > removing the constraint `Ord n`
> 
> I think constraints in type definitions such as `type` and `data` are anyway a somewhat obscure and hard-to-understand feature, and to the casual reader of the code eta-expansions are irritating.
> At least I would try to eta-contract the code and then see that I get weird compilation errors. So if there are eta-expansions to fix typing, there should be a comment saying that this eta-expansion is necessary, with link to some justification (e.g. this issue or the GHC issue).
> 
> To repeat myself, I would remove the constraints in `type`, `newtype` and `data` to get more idiomatic Haskell.

@andreasabel, thank you for your feedback. I implemented your suggestion in 03e85253bbc2528a9f94b883ca3fef81aafc355b.

**Comment by asr** [comment]
I'm getting the following error using `stack 2.5.1`:

```
$ git checkout ghc-9.0.1-stack
$ ln -s stack-9.0.1.yaml stack.yaml
$ make install-bin
...
Agda> configure (lib + exe + test)
Configuring Agda-2.6.2...
Progress 1/2
Prelude.chr: bad argument: 2382365296
```

Can anyone reproduce the error?

**Comment by andreasabel** [comment]
I tried, but then I hit #5230.

**Comment by andreasabel** [comment]
Confirming: `stack` crashed after building everything.

After 1 hour:
```
[394 of 394] Compiling Agda.Main
Preprocessing executable 'agda' for Agda-2.6.2..
Building executable 'agda' for Agda-2.6.2..
[1 of 1] Compiling Main
Linking .stack-work/dist/x86_64-osx/Cabal-3.4.0.0/build/agda/agda ...
...
[62 of 62] Compiling Main
Linking .stack-work/dist/x86_64-osx/Cabal-3.4.0.0/build/agda-tests/agda-tests ...
```
Tons of these warnings (irrelevant):
```            
Warning: Failed to decode module interface:
         /Users/abel/agda-erasure/.stack-work/dist/x86_64-osx/Cabal-3.4.0.0/build/Paths_Agda.hi
         Decoding failure: not enough bytes
...
```
Finally,
```
Progress 1/2
Prelude.chr: bad argument: 2936013004
make: *** [Makefile:150: install-bin] Error 1
```
So similar _bad argument_ than yours (but not the same).
```
$ stack --version
Version 2.5.1.1 x86_64 hpack-0.33.0
```

**Comment by asr** [comment]
There are other projects getting a similar error to

```
...
Agda> configure (lib + exe + test)
Configuring Agda-2.6.2...
Progress 1/2
Prelude.chr: bad argument: 2382365296
```

See https://github.com/commercialhaskell/stack/issues/5486.

**Comment by nad** [comment]
Perhaps we can enable `-Winvalid-haddock`.

**Comment by andreasabel** [comment]
> Perhaps we can enable `-Winvalid-haddock`.

I googled in vain for this option, could you please post a link to its description?

**Comment by nad** [comment]
https://downloads.haskell.org/~ghc/9.0.1/docs/html/users_guide/using-warnings.html#ghc-flag--Winvalid-haddock

**Comment by andreasabel** [comment]
> [downloads.haskell.org/~ghc/9.0.1/docs/html/users_guide/using-warnings.html#ghc-flag--Winvalid-haddock](https://downloads.haskell.org/~ghc/9.0.1/docs/html/users_guide/using-warnings.html#ghc-flag--Winvalid-haddock)

Thanks!  Google doesn't understand versioning of the GHC manual, so it always shows me old versions.

Does `-Winvalid-haddock` address https://github.com/agda/agda/issues/4955#issuecomment-783752784 or is it an unrelated suggestion?

**Comment by nad** [comment]
I would be surprised if that warning option could be used to fix the "bad argument" problem.

**Comment by asr** [comment]
I filed #5297 for the issue with stack.

**Comment by andreasabel** [comment]
Great, done!
