### ISSUE TITLE
hTags does not compile with ghc-7.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#1142]
```
After some necessary version bumps I guet

src/hTags$ cabal build
[1 of 2] Compiling Tags             ( Tags.hs, 
dist/build/hTags/hTags-tmp/Tags.o )

Tags.hs:197:7:
    Not in scope: data constructor ‘TyDecl’
    Perhaps you meant ‘SynDecl’ (imported from HsSyn)

Tags.hs:197:16:
    ‘tcdTyDefn’ is not a (visible) constructor field name

Tags.hs:197:28: Not in scope: data constructor ‘TyData’

Tags.hs:197:37: ‘td_cons’ is not a (visible) constructor field name

The GHC internal syntax has changed from
  http://www.haskell.org/ghc/docs/7.6.3/html/libraries/ghc/HsDecls.html#t:TyClDecl
to
  http://www.haskell.org/ghc/docs/7.8.2/html/libraries/ghc/HsDecls.html#t:TyClDecl
```

Original issue reported on code.google.com by `andreas....@gmail.com` on 22 May 2014 at 1:55
