### ISSUE TITLE
Build failure with `mtl-2.3.1`

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#6283]
Trying to build with the freshly released `mtl-2.3.1` I get this build error:
```
src/full/Agda/TypeChecking/Warnings.hs:63:25: error:
    Not in scope: type constructor or class ‘MonadTrans’
```
This is due to removed re-exports in `mtl-2.3`.  Seems like my work on `mtl-2.3` compatibility has bit-rot:
- #5798 

We should make sure that `Agda-2.6.3` can build correctly as `mtl-2.3` permeates the eco-system.  Atm, third-party dependency constraints that currently block the usage of `mtl-2.3`, but this will change...
