### ISSUE TITLE
Generated Haskell code does not typecheck

### ISSUE THREAD

**Issue by guillaumebrunerie** [agda/agda#2953]
The compilation to Haskell of the following code fails with a Haskell type-checking error. I only tested it with the latest commit of the stable branch. I believe it used to work with Agda 2.5.3 (I found it by upgrading to Agda 2.5.4).

```agda
open import Agda.Builtin.IO
open import Data.String.Base
open import Data.Unit

module Bug where

data D (A : Set) : Set where
  L : A → D A
  R : A → D A

data T : Set where
  Var : (s : D String) → T

test : T → String
test (Var (L "abc")) = ""
test (Var (L s)) = ""
test (Var (R s)) = ""

postulate
  main : IO ⊤
```
```
$ agda --compile Bug.agda                                                                                                                                        [0:18]
Checking Bug (/home/member/gbrunerie/Dropbox/Agda/Bug/Bug.agda).
Compiling Bug in /home/member/gbrunerie/Dropbox/Agda/Bug/Bug.agdai to /home/member/gbrunerie/Dropbox/Agda/Bug/MAlonzo/Code/Bug.hs
Calling: ghc -O -o /home/member/gbrunerie/Dropbox/Agda/Bug/Bug -Werror -i/home/member/gbrunerie/Dropbox/Agda/Bug -main-is MAlonzo.Code.Bug /home/member/gbrunerie/Dropbox/Agda/Bug/MAlonzo/Code/Bug.hs --make -fwarn-incomplete-patterns -fno-warn-overlapping-patterns
[3 of 3] Compiling MAlonzo.Code.Bug ( /home/member/gbrunerie/Dropbox/Agda/Bug/MAlonzo/Code/Bug.hs, /home/member/gbrunerie/Dropbox/Agda/Bug/MAlonzo/Code/Bug.o )
Compilation error:

/home/member/gbrunerie/Dropbox/Agda/Bug/MAlonzo/Code/Bug.hs:28:34: error:
    • Couldn't match type ‘GHC.Prim.Any’ with ‘Data.Text.Text’
      Expected type: AgdaAny
        Actual type: Data.Text.Text
    • In the second argument of ‘(==)’, namely ‘(Data.Text.pack "abc")’
      In the expression: (==) v2 (Data.Text.pack "abc")
      In a stmt of a pattern guard for
                     a case alternative:
        (==) v2 (Data.Text.pack "abc")
```
