### ISSUE TITLE
Abstract constructor not usable in function definition involving "with"

### ISSUE THREAD

**Issue by msuperdock** [agda/agda#3900]
When compiling the file `Abstract.agda` below, I get the following error:

```
Not in scope: Abstract.⊤.tt at Abstract.agda:14,17-19 (did you mean 'tt'?)
```

It seems I am unable to use `tt` at all in the right side of a function after a with-abstraction. If I change the definition of `f` to `f x = tt`, the file compiles without error.

I would expect to be able to use `tt` anywhere on the right side of a definition within the abstract block. On the other hand, if this is intended behavior, the error message could be improved. (I did mean `'tt'`, as the hint suggests, but I seem to be unable to refer to it.) My guess is that there is some issue with the auxiliary functions generated by the compiler when processing the with-construct within an abstract block.

Here's the `Abstract.agda` file:

```agda
module Abstract where

data Bool : Set where
  true : Bool
  false : Bool

abstract

  data ⊤ : Set where
    tt : ⊤

  f : Bool → ⊤
  f x with x
  ... | true  = tt
  ... | false = tt
```

I'm using Agda version 2.6.0.1, in NixOS.

**Comment by andreasabel** [comment]
Works fine in Agda 2.5.4.2.  A case for running agda-bisect: https://github.com/agda/agda/blob/master/HACKING.md#finding-the-commit-that-introduced-a-regression

**Comment by andreasabel** [comment]
agda-bisect claims commit fa7ee0e679d72b4b38e774696e64419819a2015b
@jespercockx 
Date:   Fri Dec 14 23:04:50 2018 +0100
  [ fix #3434 ] Use canonical name of constructor for injectivity map
