### ISSUE TITLE
Master doesn't compile

### ISSUE THREAD

**Issue by phile314** [agda/agda#1658]
Seems to be caused by d3b38f393388f40985fcbc5e5d8d18fafc367db4
Error message:

<pre>
src/full/Agda/Syntax/Concrete.hs:992:8:
    Not in scope: data constructor ‘EtaPragma’

src/full/Agda/Syntax/Concrete.hs:993:8:
    Not in scope: data constructor ‘NoEtaPragma’

</pre>

**Comment by Saizan** [comment]
Yep, fixed at

https://github.com/agda/agda/commit/24077f6eafbb4e9e26265ed581d55501da001c20
