### ISSUE TITLE
Agda can't compile with new haskell-src-exts-1.13.5.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#692]
```
Agda (2.3.0.1) can't compile with new haskell-src-exts-1.13.5
on Debian GNU/Linux sid amd64.

> src/full/Agda/Compiler/MAlonzo/Compiler.hs:469:52:
>     Not in scope: data constructor `HS.ExplicitForall'
>     Perhaps you meant `HS.ExplicitForAll' (imported from 
Language.Haskell.Exts.Extension)

I think the patch attached will fix it.

Regards,
Kiwamu Okabe
```

Original issue reported on code.google.com by `kiw...@gmail.com` on 8 Sep 2012 at 11:31

Attachments:
- [extend-haskell-src-exts-dependenc](https://storage.googleapis.com/google-code-attachments/agda/issue-692/comment-0/extend-haskell-src-exts-dependenc)
