### ISSUE TITLE
Broken build with GHC 7.8.4 due to (new) version 1.2.2.0 of hashtables

### ISSUE THREAD

**Issue by asr** [agda/agda#2745]
```
$ make install-bin
...
Building library for hashtables-1.2.2.0..
...
[ 8 of 12] Compiling Data.HashTable.Class ( src/Data/HashTable/Class.hs, dist-2.5.4/build/Data/HashTable/Class.o )

src/Data/HashTable/Class.hs:99:70:
    Not in scope: type constructor or class ‘Word’

src/Data/HashTable/Class.hs:104:31:
    Not in scope: type constructor or class ‘Word’

src/Data/HashTable/Class.hs:104:52:
    Not in scope: type constructor or class ‘Word’
Failed to install hashtables-1.2.2.0
```
