### PR TITLE
Fix for issue #5363

### LINKED ISSUE #5363: Regression: wildcard in type of generalizable variable becomes irrelevant
Here's a minimal example:
```agda
open import Agda.Primitive

variable
  A : Set _

levelOf : A → Level
levelOf {a} _ = a
```
On current master, this raises an error:
```
Variable a is declared irrelevant, so it cannot be used here
when checking that the expression a has type Level
```
This used to work in 2.6.1, and I believe up to very recently. It is causing the build of my PR https://github.com/agda/agda/pull/5354 to fail.

It seems to be a problem specific to universe levels, as the following variant is still accepted:
```agda
postulate
  A : Set
  B : A → Set
  T : ∀ {x} → B x → Set

variable
  b : B _

aOf : T b → A
aOf {a} _ = a
```

### PR DESCRIPTION
**Pull request by jespercockx**
Fixes #5363 by distinguishing between metavariables created from generalizable variables, and metavariables that will be generalized over because they occur in the type of a generalizable meta declaration.

### CODE REVIEW

**Comment by jespercockx** [comment]
Anyone knows what this error in https://github.com/agda/agda/pull/5364/checks?check_run_id=2512128214 means?
```

Agda                             > /usr/bin/ld.gold: error: cannot find -lnuma
Agda                             > 
Agda                             > rts/posix/OSMem.c:327:0: error:
Agda                             >      error: undefined reference to 'mbind'
Agda                             > 
Agda                             > rts/posix/OSMem.c:597:0: error:
Agda                             >      error: undefined reference to 'numa_available'
Agda                             > 
Agda                             > rts/posix/OSMem.c:606:0: error:
Agda                             >      error: undefined reference to 'numa_num_configured_nodes'
Agda                             > 
Agda                             > rts/posix/OSMem.c:616:0: error:
Agda                             >      error: undefined reference to 'numa_get_mems_allowed'
Agda                             > 
Agda                             > rts/posix/OSMem.c:606:0: error:
Agda                             >      error: undefined reference to 'numa_num_configured_nodes'
Agda                             > 
Agda                             > rts/posix/OSMem.c:621:0: error:
Agda                             >      error: undefined reference to 'numa_bitmask_free'
Agda                             > 
Agda                             > rts/posix/OSMem.c:606:0: error:
Agda                             >      error: undefined reference to 'numa_num_configured_nodes'
Agda                             > 
Agda                             > rts/posix/OSThreads.c:350:0: error:
Agda                             >      error: undefined reference to 'numa_run_on_node'
Agda                             > collect2: error: ld returned 1 exit status
Agda                             > `gcc' failed in phase `Linker'. (Exit code: 1)
```
? Is it just a glitch?

**Comment by nad** [comment]
> Is it just a glitch?

I've also seen this. Does it only affect GHC 8.4.4?

**Comment by nad** [comment]
This seems to be a [GHC bug](https://gitlab.haskell.org/ghc/ghc/-/issues/15444) that can perhaps be [fixed](https://www.reddit.com/r/haskell/comments/an405v/ghc_up_installation_fails_with_error/) by installing `libnuma-dev`.

**Comment by jespercockx** [comment]
Since all the other tests are succeeding, I'm going to assume this is not a specific problem with this PR.
