### ISSUE TITLE
Support GHC 8.2.1

### ISSUE THREAD

**Issue by asr** [agda/agda#2540]
Edited on 2017-07-08: Using GHC 8.2.1 RC 3 the current issues are:

* ~Missing Travis test~
* ~GHC warnings~
* ~Broken compilation of hTags~
* ~boxes library (see https://github.com/treeowl/boxes/issues/26)~
* ~geniplate-mirror library (see https://github.com/danr/geniplate/pull/8)~
* ~hashable library (see https://github.com/tibbe/hashable/issues/142)~
* ~split library (see http://hub.darcs.net/byorgey/split/issue/7)~
* ~vector library (see https://github.com/haskell/vector/pull/161)~

**Comment by asr** [comment]
GHC 8.2.1 RC2 is reporting a heap exhausted error *only* on master when testing #1829:

```
$ cd test/interaction
$ make Issue1829.cmp
...
{+agda: Heap exhausted;
agda: Current maximum heap size is 4194304 bytes (4 MB).
agda: Use `+RTS -M<size>' to increase it.+}
Accept new error [y/N/q]? 
```

**Comment by andreasabel** [comment]
I think @Saizan and/or @nad should investigate whether ghc 8,2 brings #1829 back or this is just a false alarm.

**Comment by asr** [comment]
> GHC 8.2.1 RC2 is reporting a heap exhausted error *only* on master when testing #1829:

After reinstalling GHC or restarting some Travis jobs, I couldn't reproduce the problem.

**Comment by asr** [comment]
While testing the build using GHC 8.2.1 RC 3, I found the following error:

```bash
$ make install-bin
...
[15 of 49] Compiling InternalTests.TypeChecking.Coverage.SplitTree ( test/InternalTests/TypeChecking/Coverage/SplitTree.hs, dist-2.5.3/build/internal-tests/internal-tests-tmp/InternalTests/TypeChecking/Coverage/SplitTree.o )

test/InternalTests/TypeChecking/Coverage/SplitTree.hs:14:22: error:
    Variable not in scope:
      defaultArg :: a0 -> Agda.Syntax.Common.Arg Int
   |
14 |     , (3, (SplitAt . defaultArg) <$> choose (1,5) <*> (take 3 <$> listOf1 arbitrary))
   |  
```

It seems that the first report of this error in Travis was [here](https://www.travis-ci.org/agda/agda/builds/247384945).

**Comment by asr** [comment]
I can fix the error by adding

```haskell
import Agda.Syntax.Common
```

I don't understand why the importation is only required by GHC 8.2.1 RC 3. Any idea?

**Comment by andreasabel** [comment]
When I try to load this file into `ghci` it also complains about `defaultArg`.

**Comment by asr** [comment]
GHC version?

**Comment by asr** [comment]
The problem was caused by an unused module which is compiled by GHC 8.2.1 RC3 but it isn't compiled by previous versions of GHC including 8.2.1 RC 2. I think GHC 8.2.1 RC3 is doing the right thing.

**Comment by andreasabel** [comment]
> GHC version?

7.10.x

But, surely it should complain about `defaultArg`.  How could it be possibly in scope without the import?

**Comment by asr** [comment]
> But, surely it should complain about `defaultArg`.

Yes.

>  How could it be possibly in scope without the import?

It isn't possible. GHC/Cabal were ignoring the module. In your case, your load the module in GHCi and you get the expected error.

**Comment by asr** [comment]
GHC 8.2.1 was released. Except for a test case failing, Agda supports this version of GHC. I'll file a new issue for reporting the problem with the test case.

**Comment by asr** [comment]
> GHC 8.2.1 was released. Except for a test case failing, Agda supports this version of GHC. I'll file a new issue for reporting the problem with the test case.

See #2702.
