### ISSUE TITLE
agda not working well with ghci 7.0.3 , haskell platform haskell2010-1.0.0.0 . 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [agda/agda#410]
```
The problem : 
Here is the ghci buffer after load agda : 

     Prelude> :set -package Agda-2.2.10

Prelude> ioTCM "/Users/dh/agda/1.agda" Nothing ( cmd_write_highlighting_info 
"/Users/dh/agda/1.agda" "/tmp/emacs/agda2-mode533g4u" )

<interactive>:1:1: Not in scope: `ioTCM'

after I manually added : 

Prelude> :m + Agda.Interaction.GhciTop
it seems fine. 

so it seemed that the behavior of :set -package changed. 

```

Original issue reported on code.google.com by `denghao8...@gmail.com` on 23 Apr 2011 at 12:28
