### ISSUE TITLE
Our Setup.hs does not build with Cabal-3.14

### ISSUE THREAD

**Issue by andreasabel** [agda/agda#7580]
While trying to build Agda with GHC 9.12 (which uses Cabal-3.14):
```
[1 of 2] Compiling Main             ( dist-newstyle/build/x86_64-osx/ghc-9.12.20241014/Agda-2.8.0/setup/setup.hs, dist-newstyle/build/x86_64-osx/ghc-9.12.20241014/Agda-2.8.0/setup/Main.o )
dist-newstyle/build/x86_64-osx/ghc-9.12.20241014/Agda-2.8.0/setup/setup.hs:40:37: error: [GHC-83865]
    • Couldn't match type: [Char]
                     with: Distribution.Utils.Path.SymbolicPathX
                             Distribution.Utils.Path.OnlyRelative
                             Distribution.Utils.Path.DataDir
                             Distribution.Utils.Path.File
      Expected: Distribution.Utils.Path.RelativePath
                  Distribution.Utils.Path.DataDir Distribution.Utils.Path.File
                -> [Distribution.Utils.Path.RelativePath
                      Distribution.Utils.Path.DataDir Distribution.Utils.Path.File]
        Actual: FilePath -> [FilePath]
    • In the first argument of ‘concatMap’, namely ‘(expandAgdaExt pd)’
      In the first argument of ‘($)’, namely
        ‘concatMap (expandAgdaExt pd)’
      In the expression: concatMap (expandAgdaExt pd) $ dataFiles pd
   |
40 |   pd' = pd { dataFiles = concatMap (expandAgdaExt pd) $ dataFiles pd }
   |                                     ^^^^^^^^^^^^^^^^
...
```

**Comment by andreasabel** [comment]
Rather than the necessary rewrite, I suggest to get rid of `Setup.hs` altogether.

Should the location of the primitive library be non-writable---for leaving the `.agdai` files there---, we can store them in something like `.local/state/agda/build/VERSION/agda-builtins/` (or the respective XDG location on Windows).

**Comment by andreasabel** [comment]
Discussion with @UlfNorell and @nad 2025-01-15: Get rid of `Setup.hs` but implement #4338 to help packagers to build all interface files for the primitive (or any other) library:
- [ ] #4338

**Comment by L-TChen** [comment]
As a side note, `Setup.hs` is also the main blocker to build the WASM target for Agda (see #7561). (Another obscure issue about Template Haskell should have been resolved by the recent GHC.)

**Comment by andreasabel** [comment]
According to my experiments, this simple shell script also does the job of building the builtin modules for Agda:
```
cd $(agda --print-agda-data-dir)/lib/prim
for i in $(find -name "*.agda"); do agda $i; done
```
We can put this into the installation instructions and delete `Setup.hs`.
