### ISSUE TITLE
Support GHC 8.10.2 on Linux and macOS

### ISSUE THREAD

**Issue by asr** [agda/agda#4837]
GHC 8.10.2 was [announced](https://mail.haskell.org/pipermail/ghc-devs/2020-August/019131.html). I created this issue for collecting/reporting the required changes/issues.

Know issues (2020-10-02)

None

Fixed issues (2020-10-02)

* [X] #4945
* [X] https://github.com/actions/setup-haskell/pull/32

**Comment by jovenlin0527** [comment]
I can't compile Agda using Cabal. My GHC version is ghc 8.10.2, and it complains it can't find Transformer package.
```
The error message:
src\full\Agda\Utils\Maybe.hs:13:1: error:
    Could not load module ‘Control.Monad.Trans.Maybe’
    It is a member of the hidden package ‘transformers-0.5.6.2’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
13 | import Control.Monad.Trans.Maybe
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal.exe: Failed to build Agda-2.6.1. See the build log above for details.
```
Relevant line:
https://github.com/agda/agda/blob/be5cafa4a47d5952d3bc259ba076ce042c67027b/Agda.cabal#L251

**Comment by asr** [comment]
> I can't compile Agda using Cabal. My GHC version is ghc 8.10.2, and it complains it can't find Transformer package.

The problem was fixed in 020418385c14b89ec2ea462f9376ed8549a30b15.

**Comment by nad** [comment]
When I tried to compile 2dea7f2fcc6575df3662124e0e80c78afed9c141 GHC 8.10.2 seemed to get stuck on `Agda.TypeChecking.Unquote`. After I changed `GHC_OPTS` to `"+RTS -M2G -RTS"` (for 32-bit systems) I could build Agda (`make install`) in about 45 minutes:
```
real    45m10,647s
user    60m54,525s
sys     3m23,332s
```
With `"+RTS -M2.3G -RTS"` compilation went a little faster:
```
real    40m52,246s
user    58m46,242s
sys     4m43,847s
```
I think we should try to bring down the compilation time.

**Comment by rwe** [comment]
My recent small PR #4847 is failing to build on Travis under GHC 8.10.2 and hanging. I retried once and am retrying now again. The PR is a ~3 line change that should not impact the build.

(`master` is passing but that's because Travis is not reporting in on that, apparently). Maybe it's an OOM thing?

**Comment by asr** [comment]
> My recent small PR #4847 is failing to build on Travis under GHC 8.10.2 and hanging. I retried once and am retrying now again. The PR is a ~3 line change that should not impact the build.

I had similar problems when I started to use GHC 8.10.2 on Travis.

**Comment by andreasabel** [comment]
Maybe downgrade GHC on Travis for now to get CI running again?

**Comment by asr** [comment]
The OOM problem was fixed by #4854.

**Comment by nad** [comment]
How long does it take for the rest of you to compile Agda locally (`make install`) using GHC 8.10.2?

**Comment by rwe** [comment]
@nad After external dependencies, using the `stack-8.10.2.yaml`, from `make clean`, takes my computer 30min real/29min user. It's a somewhat powerful laptop (MBP2019) with 32GB of RAM. Doing the same (clean) with GHC-8.8.3 took 24min/23min. It's a single measurement but supports the notion that 8.10.2 is significantly slower.

**Comment by asr** [comment]
From the discussion on https://gitlab.haskell.org/ghc/ghc/-/issues/18550 it seems GHC 8.10.2 is broken on Windows.

**Comment by andreasabel** [comment]
Has this issue been fixed with the release of 2.6.1.1, @UlfNorell?

**Comment by andreasabel** [comment]
> How long does it take for the rest of you to compile Agda locally (`make install`) using GHC 8.10.2?

Tried it today on mac, took me around an hour (and I killed it once at module ~340/380).  I'll downgrade to 8.8.4 again.

**Comment by UlfNorell** [comment]
Takes me 30-35min with `GHC_RTS_OPTS=-M10G` in `mk/config.mk`.

I believe the OP is fixed, but I'll leave it to @asr.

**Comment by asr** [comment]
Support for GHC X.Y.Z includes Agda compilation, tools (e.j. `agda-bisect` and `hTags`) compilation and use of GHC X.Y.Z in CI (Travis and GitHub). We can not close the issue due to the problem reported in the OP.

**Comment by andreasabel** [comment]
The latest release compiles in the usual time on my Mac.
```
time cabal v1-install Agda-2.6.1.1
...
real	31m37.088s
user	29m46.628s
```

**Comment by UlfNorell** [comment]
Possibly you hit the memory limit set by the `Makefile` when compiling master?

**Comment by andreasabel** [comment]
With you 10G limit and compiling most of master, starting here:
```
[121 of 381] Compiling Agda.Utils.IO 
```
It took:
```
real	38m48.658s
user	31m35.841s
```
Feels to me like a regression in GHC, would you agree?  Have we reported this?

**Comment by nad** [comment]
My understanding is that the flags that @jespercockx turned on are not recommended. If performance is significantly worse with these flags turned off it might make sense to report a regression.

**Comment by andreasabel** [comment]
> My understanding is that the flags that @jespercockx turned on are not recommended. If performance is significantly worse with these flags turned off it might make sense to report a regression.

If I remember correctly these flags were a remedy for the 5% performance loss resulting from generalizing `TCM` computations to `m` computation where `m` satisfies a dozen `MonadSomething` constraints.  A compiler could specialize all these computations to `TCM`, getting rid of tons of dictionary-passing, but apparently GHC does not do so by default.

**Comment by solomon-b** [comment]
I'm getting the following error on nixos:
```
    Could not load module ‘Control.Monad.Trans.Identity’
    It is a member of the hidden package ‘transformers-0.5.6.2’.
    Perhaps you need to add ‘transformers’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

**Comment by asr** [comment]
Which Agda version are you using?

**Comment by solomon-b** [comment]
> Which Agda version are you using?

2.6.1

**Comment by asr** [comment]
Agda 2.6.1 does not support GHC 8.10.*. You need a recent version of Agda.
