### ISSUE TITLE
Nix build fails on aarch64-darwin

### ISSUE THREAD

**Issue by lane-core** [agda/agda#8016]
Title is self-explanatory, I was asked to create this issue along with a minimal nix flake to reproduce the issue.

@ncfavier I wonder if this is an issue specific to aarch64-darwin (assuming this is not your platform). This is, I believe, the salient message from the build log to begin investigation upon:

`"The following functions have been omitted by a nixpkgs-specific patch to Cabal: getLibDir, getDynLibDir, getLibexecDir, getSysconfDir"` used in the `Agda.Version` module.

flake.nix:
```nix
{
  description = "Test flake for Agda overlay";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    agda.url = "github:agda/agda";
    agda.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    {
      self,
      nixpkgs,
      agda,
    }:
    let
      system = "aarch64-darwin";
      pkgs = import nixpkgs {
        inherit system;
        overlays = [ agda.overlays.default ];
      };
    in
    {
      packages.${system}.default = pkgs.agda;

      devShells.${system}.default = pkgs.mkShell {
        buildInputs = [ pkgs.agda ];
      };
    };
}
```

And here's the build log:

```
$  nix build                                                                16
error: builder for '/nix/store/jdwbm8k38j9jm2ppdw8m85d1k01na49b-Agda-2.9.0.drv' failed with exit code 1;
       last 25 log lines:
       > Using strip found on system at:
       > /nix/store/cdjiamwcmyzbd48jz4nqdmxfpinp9d6w-clang-wrapper-19.1.7/bin/strip
       > Using tar found on system at:
       > /nix/store/25v7jy2zfx4mx2ca8grk8lkmyn8zbkap-gnutar-1.35/bin/tar
       > No uhc found
       > Running phase: buildPhase
       > Preprocessing executable 'agda-mode' for Agda-2.9.0..
       > Building executable 'agda-mode' for Agda-2.9.0..
       > [1 of 7] Compiling Agda.Setup.DataFiles ( src/setup/Agda/Setup/DataFiles.hs, dist/build/agda-mode/agda-mode-tmp/Agda/Setup/DataFiles.o, dist/build/agda-mode/agda-mode-tmp/Agda/Setup/DataFiles.dyn_o )
       > [2 of 7] Compiling Paths_Agda       ( dist/build/agda-mode/autogen/Paths_Agda.hs, dist/build/agda-mode/agda-mode-tmp/Paths_Agda.o, dist/build/agda-mode/agda-mode-tmp/Paths_Agda.dyn_o )
       > [3 of 7] Compiling Agda.Version     ( src/setup/Agda/Version.hs, dist/build/agda-mode/agda-mode-tmp/Agda/Version.o, dist/build/agda-mode/agda-mode-tmp/Agda/Version.dyn_o )
       >
       > src/setup/Agda/Version.hs:13:1: error: [GHC-15328] [-Wdeprecations, -Werror=deprecations]
       >     Module ‘Paths_Agda’:
       >       "The following functions have been omitted by a nixpkgs-specific patch to Cabal: getLibDir, getDynLibDir, getLibexecDir, getSysconfDir"
       >    |
       > 13 | import qualified Paths_Agda as PA
       >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >
       > src/setup/Agda/Version.hs:19:27: error: [GHC-63394] [-Wdeprecations, -Werror=deprecations]
       >     In the use of ‘version’ (imported from Paths_Agda):
       >     "The following functions have been omitted by a nixpkgs-specific patch to Cabal: getLibDir, getDynLibDir, getLibexecDir, getSysconfDir"
       >    |
       > 19 |             versionBranch PA.version
       >    |                           ^^^^^^^^^^
       For full logs, run 'nix log /nix/store/jdwbm8k38j9jm2ppdw8m85d1k01na49b-Agda-2.9.0.drv'.
error: 1 dependencies of derivation '/nix/store/4gphy2bxkh13nr4b5phnl00yzb2sl3kz-agdaWithPackages-2.9.0.drv' failed to build
```

**Comment by ncfavier** [comment]
Indeed this looks like an aarch64-darwin-specific problem. It seems like the patch mentioned in that error message was introduced in https://github.com/NixOS/nixpkgs/pull/258280, with more context in https://github.com/NixOS/nixpkgs/issues/140774.

This looks like it has to do with having a separate bin output, which I recently enabled in https://github.com/agda/agda/pull/8008. Does it work if you replace the agda input with `github:agda/agda/no-separate-bin-output`?

@sternenseemann @maralorn is `enableSeparateBinOutput` known to be broken on aarch64-darwin?

**Comment by lane-core** [comment]
> Indeed this looks like an aarch64-darwin-specific problem. It seems like the patch mentioned in that error message was introduced in [NixOS/nixpkgs#258280](https://github.com/NixOS/nixpkgs/pull/258280), with more context in [NixOS/nixpkgs#140774](https://github.com/NixOS/nixpkgs/issues/140774).
> 
> This looks like it has to do with having a separate bin output, which I recently enabled in [#8008](https://github.com/agda/agda/pull/8008). Does it work if you replace the agda input with `github:agda/agda/no-separate-bin-output`?
> 
> [@sternenseemann](https://github.com/sternenseemann) [@maralorn](https://github.com/maralorn) is `enableSeparateBinOutput` known to be broken on aarch64-darwin?

Yes, changing the input worked. Until the bigger issue gets worked out, is this branch suitable to use as a stop-gap in my system configuration flake?

**Comment by ncfavier** [comment]
Sure, I'll leave it up at least until we have a better fix.

Since the error seems to actually be just a warning treated as an error, maybe it would be enough to add `-Wwarn=deprecations` to the GHC flags on aarch64-darwin?

**Comment by sternenseemann** [comment]
If the mentioned module members aren't used, the warnings can just be ignored. If you just need the version, you can actually obtain it without the `Paths_` module which is notorious for causing unnecessary references: <https://github.com/PostgREST/postgrest/commit/c045b261c4f7d2c2514e858120950be6b3ddfba8>.

**Comment by ncfavier** [comment]
Thanks. We do also [use](https://github.com/agda/agda/blob/f1d5e5ec2828911074ab1a8f49fa3e8956b2e612/src/setup/Agda/Setup.hs#L117) `getDataDir` from `Paths_Agda`, so it looks like ignoring the warning would be the way.

@lane-core could you try again with `github:agda/agda/ignore-deprecations-aarch64-darwin`? If that works I'll open a PR and delete the other branch.

**Comment by lane-core** [comment]
> Thanks. We do also [use](https://github.com/agda/agda/blob/f1d5e5ec2828911074ab1a8f49fa3e8956b2e612/src/setup/Agda/Setup.hs#L117) `getDataDir` from `Paths_Agda`, so it looks like ignoring the warning would be the way.
> 
> [@lane-core](https://github.com/lane-core) could you try again with `github:agda/agda/ignore-deprecations-aarch64-darwin`? If that works I'll open a PR and delete the other branch.

Confirming that I was able to build this successfully! thank you @ncfavier
