### ISSUE TITLE
test/interaction/Issue1829.agda fails sometimes with GHC 8.2.1 (only in master)

### ISSUE THREAD

**Issue by asr** [agda/agda#2702]
In master, sometimes I got this error with GHC 8.2.1 when testing #1829:

```
$ make interaction
...
agda2-info-action "*Type-checking*" "Checking Issue1829 (Issue1829.agda). " t)
{+agda: Heap exhausted;
agda: Current maximum heap size is 4194304 bytes (4 MB).
agda: Use `+RTS -M<size>' to increase it.+}
```

If I run `make interaction` again, the problem disappears. Travis also has the same behaviour, that is, sometimes `test/interaction/Issue1829.agda` fails (see for example jobs [265498079](https://www.travis-ci.org/agda/agda/jobs/265498079) or [265087070](https://www.travis-ci.org/agda/agda/builds/265087070)) but the problems disappears if I re-start the job.

**Comment by asr** [comment]
In a previous report of this problem, @andreasabel [wrote](https://github.com/agda/agda/issues/2540#issuecomment-300066961):

>I think @Saizan and/or @nad should investigate whether ghc 8.2 brings #1829 back or this is just a false alarm.

**Comment by Saizan** [comment]
Memory use does grow with a longer Issue1829.in, while it's supposed to be constant.

So we do have an issue here.

**Comment by Saizan** [comment]
Some investigation:

It seems unrelated to --caching.

Without passing the --caching flag: using a 25k lines long Issue1829.in we get that all 4 of agda master and stable-2.5 compiled both with 8.0.2 and 8.2.1 exhaust an heap of 10MB while they all do fine against a 1k lines long Issue1829.in

**Comment by nad** [comment]
I fed 25000 lines of input to Agda 2.6.0-439fe3e (roughly), built using GHC 8.2.1, with a 20M heap, and got the following `-h` heap profile:

![1829](https://user-images.githubusercontent.com/293222/29604685-9a8c6916-87e8-11e7-82f3-c7a135c33064.png)

This profile is consistent with the changes I implemented for #2217, in which I added a command queue, and a process that reads commands and places them on the queue. I guess that if we only feed Agda another command once the first has completed (like in the Emacs mode), then the memory consumption will be much lower.

**Comment by Saizan** [comment]
Oh, that explains why the heap exhausted error is thrown after not much of the usual interaction output. I was not aware of this command queue.

**Comment by andreasabel** [comment]
@nad I seems you should also commit the new `Issue1829.out` file.

**Comment by andreasabel** [comment]
Ok, I do it.

**Comment by andreasabel** [comment]
Actually, it does not work on ghc-7.10:
```
Issue1829.hs:61:3:
    Not in scope: ‘withCreateProcess’
    Perhaps you meant one of these:
      data constructor ‘CreateProcess’ (imported from System.Process),
      ‘readCreateProcess’ (imported from System.Process)
```

**Comment by nad** [comment]
It works on GHC 7.6.3 if you have installed a sufficiently recent version of process (>= 1.4.3.0). Sufficiently recent versions of process ship with GHC 8.0.2 and 8.2.1.

I'll remove the use of `withCreateProcess`.
