### PR TITLE
Fix #6283: build with mtl-2.3.1

### LINKED ISSUE #6283: Build failure with `mtl-2.3.1`
Trying to build with the freshly released `mtl-2.3.1` I get this build error:
```
src/full/Agda/TypeChecking/Warnings.hs:63:25: error:
    Not in scope: type constructor or class ‘MonadTrans’
```
This is due to removed re-exports in `mtl-2.3`.  Seems like my work on `mtl-2.3` compatibility has bit-rot:
- #5798 

We should make sure that `Agda-2.6.3` can build correctly as `mtl-2.3` permeates the eco-system.  Atm, third-party dependency constraints that currently block the usage of `mtl-2.3`, but this will change...

### PR DESCRIPTION
**Pull request by andreasabel**
Some reexports got removed in `mtl` 2.3 over 2.2.

### CODE REVIEW

**Comment by andreasabel** [comment]
@asr: This commit needs to go into 2.6.3.  Please cherry-pick or fast-forward.

**Comment by asr** [comment]
Done.
